
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Jul 26 23:01:16 CEST 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 7;
  public static final int CHAR = 45;
  public static final int CONST = 3;
  public static final int EQUALS = 12;
  public static final int LPAREN = 5;
  public static final int SEMI = 4;
  public static final int CONTINUE = 31;
  public static final int L = 37;
  public static final int G = 35;
  public static final int MINUS = 15;
  public static final int RPAREN = 6;
  public static final int AND = 39;
  public static final int OR = 40;
  public static final int BOOL = 44;
  public static final int COMMA = 11;
  public static final int CLASS = 27;
  public static final int INC = 19;
  public static final int DIV = 17;
  public static final int GEQ = 36;
  public static final int NUM = 46;
  public static final int PLUS = 14;
  public static final int IF = 24;
  public static final int DOT = 42;
  public static final int EOF = 0;
  public static final int RETURN = 13;
  public static final int RBRACKET = 8;
  public static final int NEW = 23;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 16;
  public static final int MOD = 18;
  public static final int NEQ = 34;
  public static final int IDENT = 47;
  public static final int BREAK = 26;
  public static final int VOID = 22;
  public static final int EQ = 33;
  public static final int ARROW = 43;
  public static final int COLON = 41;
  public static final int FOREACH = 32;
  public static final int LBRACE = 9;
  public static final int ELSE = 25;
  public static final int READ = 29;
  public static final int WHILE = 28;
  public static final int RBRACE = 10;
  public static final int EXTENDS = 30;
  public static final int LEQ = 38;
  public static final int DEC = 20;
  public static final int PRINT = 21;
}

