
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jul 23 19:22:48 CEST 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 41;
  public static final int CHAR = 45;
  public static final int CONST = 25;
  public static final int EQUALS = 9;
  public static final int UMINUS = 38;
  public static final int UPLUS = 37;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int CONTINUE = 27;
  public static final int L = 33;
  public static final int MINUS = 12;
  public static final int G = 31;
  public static final int RPAREN = 7;
  public static final int AND = 35;
  public static final int OR = 36;
  public static final int BOOL = 44;
  public static final int COMMA = 8;
  public static final int CLASS = 21;
  public static final int DIV = 14;
  public static final int GEQ = 32;
  public static final int NUM = 46;
  public static final int PLUS = 11;
  public static final int IF = 18;
  public static final int DOT = 40;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int RBRACKET = 42;
  public static final int NEW = 23;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 13;
  public static final int MOD = 15;
  public static final int NEQ = 30;
  public static final int IDENT = 47;
  public static final int BREAK = 20;
  public static final int VOID = 17;
  public static final int EQ = 29;
  public static final int ARROW = 43;
  public static final int COLON = 39;
  public static final int FOREACH = 28;
  public static final int LBRACE = 3;
  public static final int ELSE = 19;
  public static final int READ = 24;
  public static final int WHILE = 22;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 26;
  public static final int LEQ = 34;
  public static final int PRINT = 16;
}

